<a href="https://colab.research.google.com/github/prncrlnd/Test/blob/main/Numpy_and_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

# **Lists**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **Numpy Arrays**

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.06338268, 0.01779852, 0.93444417, 0.76843375],
       [0.52117888, 0.06460962, 0.13448786, 0.34862727],
       [0.26583087, 0.51023121, 0.72054409, 0.57839231]])

# **Tensors**

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8526,  1.1776, -0.3324,  0.7903],
        [-0.1423, -0.6831, -0.2532, -0.3141],
        [ 1.7529,  0.0035, -1.3296,  1.4061]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0634, 0.0178, 0.9344, 0.7684],
        [0.5212, 0.0646, 0.1345, 0.3486],
        [0.2658, 0.5102, 0.7205, 0.5784]], dtype=torch.float64)